const logos = (prefix, sender) => {
  
  return `
╭━━━━━•𖧹❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ💖❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ𖧹•━━━━━╮
         ༺𝐌𝐄𝐍𝐔 𝐋𝐎𝐆𝐎𝐒༻              
╰━━━━━•𖧹❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ💖❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ𖧹•━━━━━╯

╭━━━━━•𖧹❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ🩸❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ𖧹•━━━━━╮
┠➥ ${prefix}Angelwing
┠➥ ${prefix}Blackpink
┠➥ ${prefix}Girlmascote
┠➥ ${prefix}Logogame
┠➥ ${prefix}Equipemascote
┠➥ ${prefix}Fpsmascote
┠➥ ${prefix}Hackneon
┠➥ ${prefix}Ffavatar
┠➥ ${prefix}Mascotegame
┠➥ ${prefix}Wingeffect
┠➥ ${prefix}Angelglx
┠➥ ${prefix}Gizquadro
┠➥ ${prefix}Txtquadradinhos
┠➥ ${prefix}Starballons
┠➥ ${prefix}Frozen
┠➥ ${prefix}3dsilver
┠➥ ${prefix}Goldtext
┠➥ ${prefix}Cria
┠➥ ${prefix}Anime1
┠➥ ${prefix}Ff1
┠➥ ${prefix}Game
┠➥ ${prefix}Ff2
┠➥ ${prefix}Anime2
┠➥ ${prefix}Entardecer
┠➥ ${prefix}Indian
┠➥ ${prefix}Ffrose
┠➥ ${prefix}Ffgren
┠➥ ${prefix}Chufuyu
┠➥ ${prefix}Wolf
┠➥ ${prefix}Dragonred
┠➥ ${prefix}Avatar
┠➥ ${prefix}Chinesa
┠➥ ${prefix}Vietnam
┠➥ ${prefix}Tailandia
┠➥ ${prefix}Indonesia
┠➥ ${prefix}Japonesa 
┠➥ ${prefix}Amped  
┠➥ ${prefix}Graffiti  
┠➥ ${prefix}Graffiti-3D  
┠➥ ${prefix}Graffiti-Street  
┠➥ ${prefix}Grunge-Gray  
┠➥ ${prefix}Peace  
┠➥ ${prefix}Street-Sport  
┠➥ ${prefix}Urban-Style  
┠➥ ${prefix}Comics  
┠➥ ${prefix}Chip-Away  
┠➥ ${prefix}3D  
┠➥ ${prefix}Smurfs  
┠➥ ${prefix}Fluffy  
┠➥ ${prefix}Fabulous  
┠➥ ${prefix}Blackbird  
┠➥ ${prefix}Style  
┠➥ ${prefix}Water  
┠➥ ${prefix}Runner  
┠➥ ${prefix}Carved  
┠➥ ${prefix}World-Cup-2014  
┠➥ ${prefix}April-Fools  
┠➥ ${prefix}Glow  
┠➥ ${prefix}Thanksgiving1  
┠➥ ${prefix}Global  
┠➥ ${prefix}Winner  
┠➥ ${prefix}Neon  
┠➥ ${prefix}Clan  
┠➥ ${prefix}Harry-Potter  
┠➥ ${prefix}Birdy  
┠➥ ${prefix}Graffiti-Burn  
┠➥ ${prefix}Supermarket  
┠➥ ${prefix}Retro  
┠➥ ${prefix}Steel  
┠➥ ${prefix}Fortune  
┠➥ ${prefix}Beauty  
┠➥ ${prefix}Crafts  
┠➥ ${prefix}Chrominium  
┠➥ ${prefix}Fire  
┠➥ ${prefix}Heavy-Metal  
┠➥ ${prefix}Silver  
┠➥ ${prefix}Be-My-Valentine  
┠➥ ${prefix}Minions  
┠➥ ${prefix}Bevel-Emboss  
┠➥ ${prefix}Standing3D  
┠➥ ${prefix}Bubble  
┠➥ ${prefix}Easter-Parade  
┠➥ ${prefix}Business  
┠➥ ${prefix}Roman  
┠➥ ${prefix}Swordfire  
┠➥ ${prefix}Uprise  
┠➥ ${prefix}Fancy  
┠➥ ${prefix}Gold  
┠➥ ${prefix}Superfit  
┠➥ ${prefix}Mardi-Gras  
┠➥ ${prefix}Surfboard-White  
┠➥ ${prefix}Inferno  
┠➥ ${prefix}Star-Wars  
┠➥ ${prefix}Great-Gatsby  
┠➥ ${prefix}Flame  
┠➥ ${prefix}Brushed-Metal  
┠➥ ${prefix}Gradient-Shadow  
┠➥ ${prefix}Cookies  
┠➥ ${prefix}Colored  
┠➥ ${prefix}Outline  
┠➥ ${prefix}Orlando  
┠➥ ${prefix}Wild  
┠➥ ${prefix}Cherry  
┠➥ ${prefix}Adidas  
┠➥ ${prefix}Northern-Lights  
┠➥ ${prefix}Fifties  
┠➥ ${prefix}Parrot  
┠➥ ${prefix}Shrek  
┠➥ ${prefix}Birthday-Fun  
┠➥ ${prefix}Independence-Day  
┠➥ ${prefix}Happy-Ramadan-Silver  
┠➥ ${prefix}Golden  
┠➥ ${prefix}Cereal  
┠➥ ${prefix}Sugar  
┠➥ ${prefix}Aloha  
┠➥ ${prefix}Colored2  
┠➥ ${prefix}Glossy  
┠➥ ${prefix}San-Andreas  
┠➥ ${prefix}Cloud  
┠➥ ${prefix}Meme  
┠➥ ${prefix}Robot  
┠➥ ${prefix}Matrix  
┠➥ ${prefix}Magic  
┠➥ ${prefix}Fun-And-Play  
┠➥ ${prefix}Marbles  
┠➥ ${prefix}Signature  
┠➥ ${prefix}Restaurant  
┠➥ ${prefix}Baby  
┠➥ ${prefix}Chocolateria  
┠➥ ${prefix}Plain  
┠➥ ${prefix}Funtime  
┠➥ ${prefix}Ninja  
┠➥ ${prefix}Ice  
┠➥ ${prefix}Tattoo  
┠➥ ${prefix}Skate  
┠➥ ${prefix}Popsicle  
┠➥ ${prefix}Lava  
┠➥ ${prefix}Bold-Gold  
┠➥ ${prefix}Licorice-Allsorts  
┠➥ ${prefix}Trance  
┠➥ ${prefix}Angels-And-Demons  
┠➥ ${prefix}Fireworks  
┠➥ ${prefix}Amazing-3D  
┠➥ ${prefix}Prime  
┠➥ ${prefix}Detective  
┠➥ ${prefix}Thanksgiving2  
┠➥ ${prefix}Elegant  
┠➥ ${prefix}Drive-In-Cinema  
┠➥ ${prefix}Colgate  
┠➥ ${prefix}My-Love  
┠➥ ${prefix}Kryptonite  
┠➥ ${prefix}Genius  
┠➥ ${prefix}Casino  
┠➥ ${prefix}Tagline  
┠➥ ${prefix}Plasma  
┠➥ ${prefix}Gimp-Org  
┠➥ ${prefix}Yolo  
┠➥ ${prefix}Oscar  
┠➥ ${prefix}Jackpot  
┠➥ ${prefix}Basic2  
┠➥ ${prefix}Swing  
┠➥ ${prefix}Sweets  
┠➥ ${prefix}Skywalker  
┠➥ ${prefix}Aladdin  
┠➥ ${prefix}Splat  
┠➥ ${prefix}Easter-Gold  
┠➥ ${prefix}Picnic  
┠➥ ${prefix}Commando  
┠➥ ${prefix}Tropical  
┠➥ ${prefix}Jade  
┠➥ ${prefix}Zilch  
┠➥ ${prefix}Big-Blue  
┠➥ ${prefix}Blues  
┠➥ ${prefix}Good-Times  
┠➥ ${prefix}St-Patricks3  
┠➥ ${prefix}Monster  
┠➥ ${prefix}Scribble  
┠➥ ${prefix}Enviro  
┠➥ ${prefix}Fun  
┠➥ ${prefix}Mothers-Day3  
┠➥ ${prefix}Orange  
┠➥ ${prefix}Maven  
┠➥ ${prefix}Dance  
┠➥ ${prefix}Starscape  
┠➥ ${prefix}Booking  
┠➥ ${prefix}Dracula  
┠➥ ${prefix}Twitter  
┠➥ ${prefix}Love-Sunburst  
┠➥ ${prefix}Drop-Shadow  
┠➥ ${prefix}Happy-Ramadan-Soft  
┠➥ ${prefix}Jumbo  
┠➥ ${prefix}Old-Stone  
┠➥ ${prefix}Chocoholic  
┠➥ ${prefix}TV-Drop  
┠➥ ${prefix}Flammen  
┠➥ ${prefix}Happy-New-Year  
┠➥ ${prefix}Runescape  
┠➥ ${prefix}Cool  
┠➥ ${prefix}Kwanzaa  
┠➥ ${prefix}Express  
┠➥ ${prefix}Art-Deco  
┠➥ ${prefix}Husky  
┠➥ ${prefix}Mello-Yello  
┠➥ ${prefix}Vintage-Racing  
┠➥ ${prefix}Cams-Diner  
┠➥ ${prefix}Futurama  
┠➥ ${prefix}Magical  
┠➥ ${prefix}Sports  
┠➥ ${prefix}On-Air  
┠➥ ${prefix}Stepz  
┠➥ ${prefix}Adventure  
┠➥ ${prefix}3D-Outline  
┠➥ ${prefix}Gummy  
┠➥ ${prefix}Happy-Independence-Day  
┠➥ ${prefix}Disco-Party  
┠➥ ${prefix}Karaoke-Bar  
┠➥ ${prefix}Night-Out  
┠➥ ${prefix}Everest  
┠➥ ${prefix}Crazy  
┠➥ ${prefix}Groovy  
┠➥ ${prefix}Halloween  
┠➥ ${prefix}Soho-Chic  
┠➥ ${prefix}Holiday  
┠➥ ${prefix}Chrome  
┠➥ ${prefix}Daddy  
┠➥ ${prefix}Outline-Shadow  
┠➥ ${prefix}Medieval  
┠➥ ${prefix}Sweetie  
┠➥ ${prefix}Spider-Men  
┠➥ ${prefix}Earth-Day  
┠➥ ${prefix}Viking  
┠➥ ${prefix}Tiger  
┠➥ ${prefix}Aurora
╰━━━━━•𖧹❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭❀⃘࣭࣭࣭࣭ٜꔷ⃔໑࣭࣭ٜ𖧹•━━━━━╯
`;
};

exports.logos = logos;